juegote/urls.py
from django.urls import path
from . import views

app_name = "juegote"

urlpatterns = [
    path('<int:identificador>', views.listar_preguntas, name='listar_preguntas'),
    # cuando en la url nos venga el string /preguntas/ va a ser manejada por la vista preguntas
    path('preguntas', views.preguntas, name='preguntas'),
    path("detalle_pregunta/<int:identificador>",
         views.detalle_pregunta, name="detalle_pregunta"),
    path('crear', views.crear_pregunta, name='crear_pregunta'),
    path("editar_pregunta/<int:identificador>",
         views.editar_pregunta, name="editar_pregunta"),
    path('eliminar/<int:identificador>',
         views.eliminar_pregunta, name='eliminar'),
    path('confirmar_eliminacion/<int:identificador>',
         views.confirmar_eliminacion, name='confirmar_eliminacion'),

    path('listar_respuestas', views.listar_respuestas, name="respuestas"),
    path("detalle_respuesta/<int:identificador>",
         views.detalle_respuesta, name="detalle_respuesta"),
    path('crear_respuesta', views.crear_respuesta, name='crear_respuesta'),
    path("editar_respuesta/<int:identificador>",
         views.editar_repuesta, name="editar_respuesta"),
    path('eliminar_respuesta/<int:identificador>',
         views.eliminar_respuesta, name='eliminar_respuesta'),
    path('confirmar_resp_eliminacion/<int:identificador>',
         views.confirmar_resp_eliminacion, name='confirmar_resp_eliminacion'),

    path('categorias', views.elegir_categorias, name='categorias'),
    path('preguntas_categorias', views.preguntas_categorias,
         name='preguntas_categorias'),
    path('categoria/<int:id>', views.categoria_page, name='categoria'),
    path('', views.elegir_categorias, name='categorias'),

]

pnuevo/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario.views import registro, login, logout, home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('juegote/', include('juegote.urls')),
    path('', include('usuario.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

juegote/models.py
# Create your models here.

from django.db import models


class Pregunta(models.Model):
    autor = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    pregunta = models.CharField(max_length=500)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    id_categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)

    def __str__(self):
        return self.pregunta


class Respuesta(models.Model):
    id_pregunta = models.ForeignKey('Pregunta', on_delete=models.CASCADE)
    opcion = models.CharField(max_length=500)
    puntaje = models.IntegerField()


class Partida(models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    resultado = models.IntegerField()


class Categoria(models.Model):
    categoria = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=800)

    def __str__(self):  # De esta manera cuando hago referencia a algo relacionado a categoria directamente aparecen los nombres correctos
        return self.categoria

juegote/forms.py
from django import forms
from .models import Pregunta, Respuesta


class PreguntaForm(forms.ModelForm):

    class Meta:
        model = Pregunta
        fields = ('pregunta', 'id_categoria')


class RespuestaForm(forms.ModelForm):

    class Meta:
        model = Respuesta
        # Vamos a models y vemos que campos (fields) tenemos disponibles
        fields = ('id_pregunta', 'opcion', 'puntaje')

juegote/views.py
from django.shortcuts import render, redirect
from .models import Categoria, Pregunta, Respuesta, Partida
from datetime import datetime
from django.contrib.auth.decorators import login_required
from .forms import PreguntaForm
from .forms import RespuestaForm
from django.contrib.auth.decorators import permission_required

# Create your views here.


@login_required(login_url='/login')
# la expresion correcta de view y eso lo vemos en el admin de la app
def elegir_categorias(request):
    # Usa el modelo Categoria y se trae todos los modelos que tiene. Se trae todas las preguntas de la BD y las renderiza
    # Tengo la opcion de id, categoria, descripcion, pregunta (supongo que sacadas de models)
    categorias = Categoria.objects.all().order_by('categoria')
    agrupados = {
        'categorias': categorias
    }
    return render(request, 'juegote/categorias.html', {"categorias": categorias})


def categoria_page(request, id):
    return None


@login_required(login_url='/login')
# la expresion correcta de view y eso lo vemos en el admin de la app
def preguntas_categorias(request,  identificador):
    preguntitas = Categoria.objects.get(pk=identificador)
    return render(request, 'juegote/preguntas_categorias.html', {"preguntitas": preguntitas})


@login_required(login_url='/login')
def listar_preguntas(request, identificador):
    if request.method == "POST":
        resultado = 0
        numero_preguntas = len(Pregunta.objects.filter(
            id_categoria_id=identificador))
        data = {}
        for i in range(1, numero_preguntas+1):
            opcion = Respuesta.objects.get(pk=request.POST[str(i)])
            resultado += opcion.puntaje
            pregunta = Pregunta.objects.get(pk=opcion.id_pregunta_id)
            data[pregunta] = [opcion.opcion, opcion.puntaje]
        Partida.objects.create(usuario=request.user,
                               fecha=datetime.now, resultado=resultado)
        return render(request, 'juegote/resultados.html', {"data": data, "resultado": resultado})
    else:
        data = {}
        preguntas = Pregunta.objects.filter(id_categoria_id=identificador).order_by(
            '?')[:]  # Cuantas preguntas se van a mostrar
        for item in preguntas:
            respuestas = Respuesta.objects.filter(id_pregunta=item.id)
            categoria = Categoria.objects.get(pk=item.id_categoria.id)
            # {pregunta: {opciones: [opcion1, opcion2, opcion] categoria: categoria}
            data[item.pregunta] = {
                "opciones": respuestas, "categoria": categoria}

        return render(request, 'juegote/listar_preguntas.html', {"preguntas": preguntas, "data": data})


@login_required(login_url='/login')
# la expresion correcta de view y eso lo vemos en el admin de la app
@permission_required('juegote.view_pregunta', login_url='/login')
def preguntas(request):
    # Usa el modelo Pregunta y se trae todos los modelos que tiene. Se trae todas las preguntas de la BD y las renderiza
    preguntas = Pregunta.objects.all()
    return render(request, 'juegote/preguntas.html', {"preguntas": preguntas})


@login_required(login_url='/login')
# la expresion correcta de view y eso lo vemos en el admin de la app
@permission_required('juegote.view_pregunta', login_url='/login')
def detalle_pregunta(request, identificador):
    pregunta = Pregunta.objects.get(pk=identificador)
    return render(request, 'juegote/detalle_pregunta.html', {"pregunta": pregunta})


@login_required(login_url='/login')
# la expresion correcta de add y eso lo vemos en el admin de la app
@permission_required('juegote.add_pregunta', login_url='/login')
def crear_pregunta(request):
    form = PreguntaForm()
    if request.method == "POST":
        form = PreguntaForm(request.POST)
        if form.is_valid():
            registro = form.save(commit=False)
            registro.autor = request.user
            registro.fecha_creacion = datetime.now()
            registro.save()
            return redirect('juegote:preguntas')
    return render(request, 'juegote/crear_pregunta.html', {'form': form})


@login_required(login_url='/login')
# la expresion correcta de edit y eso lo vemos en el admin de la app
@permission_required('juegote.edit_pregunta', login_url='/login')
def editar_pregunta(request, identificador):
    pregunta = Pregunta.objects.get(pk=identificador)
    if request.method == "POST":
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            item = form.save(commit=False)
            item.autor = request.user
            item.fecha_creacion = datetime.now()
            item.save()
            return redirect('juegote:detalle_pregunta', identificador=item.id)
    else:
        form = PreguntaForm(instance=pregunta)
    return render(request, 'juegote/editar_pregunta.html', {'form': form})


@login_required(login_url='/login')
# la expresion correcta de delete y eso lo vemos en el admin de la app
@permission_required('juegote.delete_pregunta', login_url='/login')
def eliminar_pregunta(request, identificador):
    pregunta = Pregunta.objects.get(pk=identificador)
    return render(request, 'juegote/eliminar_pregunta.html', {"pregunta": pregunta})


def confirmar_eliminacion(request, identificador):
    Pregunta.objects.get(pk=identificador).delete()
    return redirect("/")


@login_required(login_url='/login')
# la expresion correcta de view y eso lo vemos en el admin de la app
@permission_required('juegote.view_respuesta', login_url='/login')
def listar_respuestas(request):
    # Usa el modelo Pregunta y se trae todos los modelos que tiene. Se trae todas las preguntas de la BD y las renderiza
    respuestas = Respuesta.objects.all()
    return render(request, 'juegote/listar_respuestas.html', {"respuestas": respuestas})


@login_required(login_url='/login')
# la expresion correcta de view y eso lo vemos en el admin de la app
@permission_required('juegote.view_respuesta', login_url='/login')
def detalle_respuesta(request, identificador):
    respuesta = Respuesta.objects.get(pk=identificador)
    return render(request, 'juegote/detalle_respuesta.html', {"respuesta": respuesta})


@login_required(login_url='/login')
# la expresion correcta de add y eso lo vemos en el admin de la app
@permission_required('juegote.add_respuesta', login_url='/login')
def crear_respuesta(request):
    form = RespuestaForm()
    if request.method == "POST":
        # Lo vamos a crear de la misma forma que creamos en forms.py
        form = RespuestaForm(request.POST)
        if form.is_valid():
            form.save()  # A diferencia del anterior, el commit era False porque tambien le ibamos a agregar fecha de creacion y autor, en este caso no tenemos ninguno de los dos asi que podemos ponerle que guarde en la BD
            return redirect('juegote:respuestas')
    return render(request, 'juegote/crear_respuesta.html', {'form': form})


@login_required(login_url='/login')
# la expresion correcta de change y eso lo vemos en el admin de la app
@permission_required('juegote.change_respuesta', login_url='/login')
def editar_repuesta(request, identificador):
    pregunta = Respuesta.objects.get(pk=identificador)
    if request.method == "POST":
        # Lo vamos a crear de la misma forma que creamos en forms.py
        form = RespuestaForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
            return redirect('juegote:detalle_respuesta', identificador=item.id)
    else:
        # Tambien la vamos a crear en forms.py
        form = RespuestaForm(instance=pregunta)
    return render(request, 'juegote/editar_respuesta.html', {'form': form})


@login_required(login_url='/login')
# la expresion correcta de delete y eso lo vemos en el admin de la app
@permission_required('juegote.delete_respuesta', login_url='/login')
def eliminar_respuesta(request, identificador):
    pregunta = Respuesta.objects.get(pk=identificador)
    return render(request, 'juegote/eliminar_respuesta.html', {"pregunta": pregunta})


@login_required(login_url='/login')
# la expresion correcta de delete y eso lo vemos en el admin de la app
@permission_required('juegote.delete_respuesta', login_url='/login')
def confirmar_resp_eliminacion(request, identificador):
    Respuesta.objects.get(pk=identificador).delete()
    return redirect("juegote:listar_respuestas")

templates/juegote/crear_pregunta.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>


{% endblock %}

templates/juegote/crear_respuesta.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>


{% endblock %}

templates/juegote/detalle_pregunta.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    {{pregunta.autor}}
    <br>
    {{pregunta.pregunta}}
    <br>
    {{pregunta.fecha_creacion}}

{% endblock %}

templates/juegote/detalle_respuesta.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    {{respuesta.id_pregunta}}
    <br>
    {{respuesta.opcion}}
    <br>
    {{respuesta.puntaje}}

{% endblock %}

templates/juegote/editar_pregunta.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    <h2>Editar publicación</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>

templates/juegote/editar_respuesta.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    <h2>Editar publicación</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>

templates/juegote/eliminar_pregunta.html
<html>
    <head>
        <title>Info 2021</title>
    </head>
<body>
    <h2>Detalle pregunta</h2>
    {{pregunta.autor}}
    <br>
    {{pregunta.pregunta}}
    <br>
    {{pregunta.fecha_creacion}}
<a class="btn btn-default" href="{% url 'juegote:detalle_pregunta' pregunta.pk %}">Cancelar</a>
<a class="btn btn-default" href="{% url 'juegote:confirmar_eliminacion' pregunta.pk %}">Confirmar</a>
</body>
</html>

templates/juegote/eliminar_respuesta.html
<html>
    <head>
        <title>Info 2021</title>
    </head>
<body>
    <h2>Detalle pregunta</h2>
    {{respuesta.opcionr}}
    <br>
    {{respuesta.id_pregunta}}
    <br>
    {{respuesta.puntaje}}
<a class="btn btn-default" href="{% url 'juegote:detalle_respuesta' respuesta.pk %}">Cancelar</a>
<a class="btn btn-default" href="{% url 'juegote:confirmar_resp_eliminacion' respuesta.pk %}">Confirmar</a>
</body>
</html>

templates/juegote/listar_preguntas.html
{% extends "base2.html" %}
{% block titulO %}Preguntas{% endblock %}
{% block body %}

        <center><div class="row justify-content-md-center m-4">
            <div class="mb-3 row-cols-lg-6">
                    <form action="" method="POST">
                    {% csrf_token %}
                    {% for item, value in data.items %}
                        <div class="alert alert-warning" role="alert">
                            {{ item }}
                        </div>                
                        {{value.categoria}} <br>
                            <select name="{{ forloop.counter }}">
                                <option value="">---------</option>
                                {% for opcion in value.opciones %}
                                    <option value="{{ opcion.id }}">{{ opcion.opcion }}</option>
                                {% endfor %}
                            </select>
                        <br>
                    {% endfor %}
                    <br>
                    <input type="submit" value="Submit">
                    </form>
                </div>
            </div></center>
{% endblock %}

templates/juegote/listar_respuestas.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    <div class="row justify-content-md-center m-5">
        <div class="mb-3 col-lg-6">
                {% for item in respuestas %} 
            <div class="alert alert-primary" role="alert">
                {{item}}
                <a class="btn btn-primary" href="{% url 'juegote:detalle_respuesta' item.pk %}">Detalle</a>
                <a class="btn btn-danger" href="{% url 'juegote:eliminar_respuesta' item.pk %}">Eliminar</a>
            </div>
                {% endfor %}
                
        </div>
     </div>
{% endblock %}

templates/juegote/preguntas.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    <div class="row justify-content-md-center m-5">
        <div class="mb-3 col-lg-6">
                {% for item in preguntas %} 
            <div class="alert alert-primary" role="alert">{{item}}
                {{item}}
                <a class="btn btn-primary" href="{% url 'juegote:detalle_pregunta' item.pk %}">Detalle</a>
                <a class="btn btn-danger" href="{% url 'juegote:eliminar' item.pk %}">Eliminar</a>
            </div>
                {% endfor %}
                
        </div>
     </div>
{% endblock %}

templates/juegote/preguntas_categorias.html
{% extends "base2.html" %}
{% block titulo %}Proyecto Info{% endblock %}
{% block body %}
    {{pregunta.autor}}
    <br>
    {{pregunta.pregunta}}
    <br>
    {{pregunta.fecha_creacion}}

{% endblock %}

templates/juegote/preguntas_historia.html
{% extends "base.html" %}
{% block titulo %}Categorias{% endblock %}
{% block body %}


    <div class="row justify-content-md-center m-5">
        <h4>
            <center><div class="mb-3 col-lg-4">
                <div class="m-3 p-3 rounded border border-4">SELECCIONE LA CATEGORIA CON LA QUE DESEA JUGAR</div>
            </div></center>
        </h4>
        <div class="mb-3 col-lg-2">
                {% for categoria in categorias %} 
            <div class="alert alert-primary" role="alert">
                <a class="btn btn-primary" href=""{% url 'juegote:editar_pregunta' pregunta.pk %}">{{categoria.categoria}}</a>
            </div>
                {% endfor %}
        </div> 
    </div>
{% endblock %}

templates/juegote/resultados.html
{% extends "base2.html" %}
{% block titulo %}Categorias{% endblock %}
{% block body %}


    <div class="row justify-content-md-center m-5">
        <h4>
            <center><div class="mb-3 col-lg-4">
                <div class="m-3 p-3 rounded border border-4">SU RESULTADO ES:
                    {{resultado}}  
                </div>
            </div></center>
        </h4>
        <div class="mb-3 col-lg-2">
                {% for key,item in data.items %} 
                <p>{{key}}</p>
                <p>{{item.0}}</p>
                <p>{{item.1}}</p>

                {% endfor %}
        </div> 
    </div>
{% endblock %}